### ISSUE TITLE
A suggestion for git

### ISSUE THREAD

**Issue by RayYoh** [Teddy-Liao/walk-these-ways-go2#1]
Hi authors,

Thanks for your great work and make it available for the community.
I suggest that you can use .gitignore to ignore the update of some cache files like __pycache__. So that it will be more clear for us to identify your update.

Best

**Comment by Teddy-Liao** [comment]
Thanks for your suggestion, and I will fix this problem soon.

**Comment by RayYoh** [comment]
Hello, the author. Maybe this file [here](https://github.com/github/gitignore/blob/main/Python.gitignore) can help a lot.

**Comment by Teddy-Liao** [comment]
Hi there, the file does help a lot, thanks.
