### ISSUE TITLE
jetson and isaac gym

### ISSUE THREAD

**Issue by hanzhi0410** [Teddy-Liao/walk-these-ways-go2#10]
Is there any difference between the installation of isaac Gym in Jetson and in PC? My system will report an error
ImportError:/home/rl/IsaacGym/isaacGym/Python/isaacGym/unbinding/linux-x86_64/gym.38. so: cannot open shared object file: No such file or directory

**Comment by Teddy-Liao** [comment]
Sorry, I've never tried installing Isaac Gym on Jetson, so I recommend installing it and training models on a PC instead.

**Comment by hanzhi0410** [comment]
Thank you for your reply. I would like to ask if it is possible to deploy legged_Gym using this method. I look forward to your help

**Comment by Teddy-Liao** [comment]
You can deploy the network just by following this repo, and you can also deploy your custom neural network by libtorch, mnn or other.

**Comment by hanzhi0410** [comment]
Thank you for your reply. I have attempted to deploy my code using libtorch.
