### ISSUE TITLE
About actuator network

### ISSUE THREAD

**Issue by Riboha** [Teddy-Liao/walk-these-ways-go2#11]
Hello, thanks for your wonderful work!
Your work is helping me a lot, and I have a question.

Is the weight file of the actuator network (resources/actuator_nets/unitree_go1.pt) for unitree-go2? (Is the network trained using the data from unitree-go2?)

**Comment by Teddy-Liao** [comment]
Hello,the network is trained by Unitree Go1,which is provided by the original walk-these-ways project. You can try to train the network using Unitree Go2.

**Comment by Riboha** [comment]
Thank you for your response! I'll try on it.
