### ISSUE TITLE
Question about simulation environment

### ISSUE THREAD

**Issue by RayYoh** [Teddy-Liao/walk-these-ways-go2#6]
Dear authors,

Thanks for your excellent work. I'd like to ask are there any referred code or repo that can achieve the real-time mapping of real Go2 in simulation environment?

**Comment by Teddy-Liao** [comment]
I wonder if you mean sim-to-sim projects. You can cross-verify the neural network in Webots, Mujoco or Gazebo.

**Comment by RayYoh** [comment]
> I wonder if you mean sim-to-sim projects. You can cross-verify the neural network in Webots, Mujoco or Gazebo.

No, just visualizing the real robot states in real-time in a simulation environment (like Rviz).

**Comment by Teddy-Liao** [comment]
Just use Matplotlib to visualize robot states.
